[package]
name = "anki_integration"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
once_cell = "1.19.0"
reqwest = "0.12.4"
serde = "1.0.201"
serde_json = "1.0.117"
